version: "3.8"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,ec2,lambda,sqs,cognito-idp
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=INSERT-KEY-HERE
      - AWS_SECRET_ACCESS_KEY=INSERT-SECRET-HERE
